/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PetPetIdUploadImage {
  post: {
    Parameters: {
      path: {
        /**
         * ID of pet to update
         */
        petId: number;
      };
    };
    RequestBody: {
      'multipart/form-data': {
        /**
         * Additional data to pass to server
         */
        additionalMetadata?: string;
        /**
         * file to upload
         */
        file?: string;
      };
    };
    Responses: {
      /**
       * successful operation
       */
      '200': {
        'application/json': ApiResponse;
      };
    };
  };
}
export interface ApiResponse {
  code?: number;
  type?: string;
  message?: string;
}
